### ISSUE TITLE
Language of month name

### ISSUE THREAD

**Issue by agatap2** [hosannahighertech/MessageKit#3]
How can I change the language of month name in the date displayed above messages? It is in English by default but I need to have it in Polish.

**Comment by mtangoo** [comment]
Can you post sample screenshot to illustrate what you are asking?

**Comment by agatap2** [comment]
![ChatKit screenshot](https://user-images.githubusercontent.com/25003746/142074107-ad5c97c2-e878-44c3-900a-4d85c4dcc2a3.png)

**Comment by mtangoo** [comment]
Ok, in that case you will need to implement your own date formatter and pass it using `setFormatter` method.
Please have a look at this Sample. Let me know if you need further assistance!

https://github.com/hosannahighertech/MessageKit/blob/03b9c3557af8c6691bab42b7152986113b6f1bc9/sample/src/main/java/tz/co/hosannahighertech/messagekit/sample/features/demo/styled/StyledDialogsActivity.java#L17

**Comment by mtangoo** [comment]
I will assume this issue was fixed by solution above. 
Feel free to reopen if that is not the case!
