### ISSUE TITLE
steal code without license?

### ISSUE THREAD

**Issue by fukemy** [hosannahighertech/MessageKit#6]
I found u clone the code from this git https://github.com/stfalcon-studio/ChatKit without any license and fork description

**Comment by fukemy** [comment]
<img width="842" alt="Screen Shot 2022-12-24 at 10 46 46" src="https://user-images.githubusercontent.com/8202437/209420152-c27112e0-c81c-4425-a70c-d332964485a2.png">


Ok I just found your comment, sorry

**Comment by mtangoo** [comment]
Hi @fukemy,
the license is the same as Chatkit!
